NOTE : Using In Built Function are heavily scrutanized so please ask your section faculty before using any in exams.   

You can use len()

```
List: is a data structure which can hold multiple values.

1. Ordered. Has built in indexing starting from 0. Then 1,2,3,4...
2. Can contain multiple data types in a single list
3. Mutable. We can alter elements even after list is declared.
4. Allow duplicates  

We use 'square brackets' to represent List.

```

```
Manual Implementation needed for exam:
append()
extend()
remove()
pop()
index()
count()

```

In [ ]:
var = "123"
print(type(var))

var = int(var)
print(type(var))

<class 'str'>
<class 'int'>

In [ ]:
ori = "[1,2,4]"
print(type(ori))

ori = list(ori)
print(type(ori))

<class 'str'>
<class 'list'>

## Pass by value vs pass by referrence

In [ ]:
var1 = 5
var2 = 7

var1 = var2 #just value is passed

print(var1,var2)

var2 = 12

print(var1,var2)

7 7
7 12

In [ ]:
list1 = [4,5]
list2 = [12,16]

list1 = list2 #referrence/ address is passed

print(list1,  list2)

list2[0] = 32   #As we are changing element at index 0 of list2, elem of index list1 is also changed.

print(list1,  list2)

[12, 16] [12, 16]
[32, 16] [32, 16]



##Introduction

In [ ]:
#list created of elements of data type integer
list1 = [1,2,3,4,5]


#list created of elements of data type String. Here 1 is a string too as it is within " "(inverted comma)
list2 = ["1","A","BCD","Toyota"]


#list created of elements of data type Float. Here 1.0 is a float too
list3 = [2.3,4.6,112.4,1.0]


#Here is a list with all three data type
list4 = [2.3,"ABC",4,"1"]

#But the variable list1/list2/list3/list4 itself is LIST
print("list1 is a",type(list1))

list1 is a <class 'list'>

##Printing the list

Way 01

In [ ]:
list1 = ["A","B","C","D"]

#len(list1) gives 4 as there are 4 elements
for i in range(len(list1)):
  print(list1[i])

A
B
C
D

Way 02

In [ ]:
list1 = ["A","B","C","D"]

#Here i is first A, then B, then C and so on.
for i in list1:
  print(i)

A
B
C
D

##Taking inputs from user

### Way 01(One element at a time)

In [2]:
#First ask the user for the length of the list
length_of_list = int(input("Please enter the number of element you want to enter "))


#empty list to put the element the users enters
list1 = []


#The loop runs for the number of times user wants and take one element at a time from the user
for i in range(length_of_list):
  #if you are taking strings, no need to convert it into integer
  """ num =  """
  list1.append(int(input("Please enter an element ")))



#Printing the entire list
print(list1)

[1, 2, 34, 5, 6, 7, 8, 11, 23]

### Way 2(The whole list at a time)

In [ ]:
#First ask user to enter the total list as a whole that is needed

val = input("please enter the list ")[1:-1] #"[1,2,3]" --> "1,2,3"
#This contains a string of elemets as entered. Careful as this a string so you dont have to convert it into integer using int()
print(type(val))
list1 = val.split(",") #"1,2,3" --> ['1' ,'2', '3']
#This converts the string into a list with string elements. It splits along comma(,)
print(list1)

#Iterates over the whole list
for i in range(len(list1)):
  #converts every string element in a particular index to an integer type element
  list1[i] = int(list1[i])



print(list1)

please enter the list [1,2,3]
<class 'str'>
['1', '2', '3']
[1, 2, 3]

**Concise(Most Important)**

In [ ]:

list1 = input("please enter the list ")[1:-1].split(",")
#Here the input is first  using [1:-1]. And then split() which turns it into a list with string type elements

print("List with string type elements",list1)


for i in range(len(list1)):
 list1[i] =int(list1[i])

print("List with int type elements",list1)

please enter the list [1,2,3,4]
List with string type elements ['1', '2', '3', '4']
List with int type elements [1, 2, 3, 4]

**For Alphabets**

In [ ]:
list1 = input("please enter the list ")[1:-1].split(",")

print(list1)

#NB: Careful as this a list with character so you dont have to convert it into integer using int()

please enter the list [A,B,C,D]
['A', 'B', 'C', 'D']

`NB: If the list contains characters/alphabets(eg:'Car','Tree') as elements then we do not need to convert them into integers using loop & int()`

## Way 02 - Alternative (Without split)

In [ ]:
var = input("please enter the list ")[1:-1]  #[4,5,6,7,8,9]

print(f"String without the brackets {var} and this is of type {type(var)}")

final = []

res = ""

for chr in var:

    if chr == ",":
       final.append(int(res))  #final += [int(res)]
       res = ""

    else:
       res += chr

final.append(int(res))   #to add the last element in the list
print(final)

please enter the list [4,5,6,7,8,9]
String without the brackets 4,5,6,7,8,9 and this is of type <class 'str'>
[4, 5, 6, 7, 8, 9]

In [ ]:
var = input("please enter the list ")[1:-1] #[4,5,6,7,8,9]

var += ","    #additional , makes sures that last element is added to the list inside the loop er jonne last e , append korte hobe na
print(f"String without the brackets {var} and this is of type {type(var)}")

final = []

res = ""

for chr in var:

    if chr == ",":
       final.append(int(res)) #final += [int(res)]
       res = ""

    else:
       res += chr

print(final)

please enter the list [4,5,6,7,8,9]
String without the brackets 4,5,6,7,8,9, and this is of type <class 'str'>
[4, 5, 6, 7, 8, 9]

### Way 03 (Using List comprehension)
[More about list comprehension](https://www.w3schools.com/python/python_lists_comprehension.asp)

In [14]:
#Here after asking user for an input, the for loop will iterate through the list and convert to int
list1 = [int(elem) for (elem) in (input("please enter the list ")[1:-1].split(",")) ] #cant use in exams

print(list1)

[2]

In [ ]:
list1=input("please enter the list ")[1:-1]


list1 = [int(elem) for (elem) in (input("please enter the list ")[1:-1].split(",")) ] #cant use in exams

In [11]:
fruits = ["apple", "banana", "cherry", "kiwi", "mango"]
newlist = [ _ for _ in fruits if "a" in _ ]

print(newlist)

['apple', 'banana', 'mango']

### Way 04(Taking input of string elements with inverted comma)

`Do remember '"A"' is a string type element of the list which is of length 3 as doule inverted comma(") are also considered part of the string. `

In [ ]:
#               0123456789
#sample input = ["A","B","C"]      " is included as string here so we have to remove it
s=input("please enter your desired list")  #input()[1:-1].split(",")
s= s[1:-1] #Brackets remove
print(s)
print(type(s))
list1 = s.split(",") #'"A","B","C"' ---> ['"A"','"B"','"C"']
print("List before removing the double inverted comma",list1)


for i in range(len(list1)):#            '"A"' ---> 'A'
  list1[i] = list1[i][1:-1] #This slicing is to remove the double inverted comma from each element which is part of the string

print(list1)

please enter your desired list["A","B","C"]
"A","B","C"
<class 'str'>
List before removing the double inverted comma ['"A"', '"B"', '"C"']
['A', 'B', 'C']

In [18]:
lst=[1,2,3,4,5,6,7,8,9,10]

lst+=['a']

print(lst)

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 'a']

### Way 05(Taking input of string elements with inverted comma+without inverted comma)

In [ ]:
#sample input = ["A","B","C",1]

s=input("please enter your desired list")

s= s[1:-1] #Brackets remove

print(s)

print(type(s))

list1 = s.split(",")#'"A","B","C", 1' ---> ['"A"','"B"','"C"', '1']

print("List before removing the double inverted comma",list1)


for i in range(len(list1)):
    
  if list1[i].isdigit():
      
      list1[i] = int(list1[i])  #Here the integer (eg: 1) is converted to integer.
  else:
      
      list1[i] = list1[i][1:-1] #This slicing is to remove the double inverted comma from each element which is part of the string

print(list1)

please enter your desired list["A","B","C",1]
"A","B","C",1
<class 'str'>
List before removing the double inverted comma ['"A"', '"B"', '"C"', '1']
['A', 'B', 'C', 1]

## append vs \[        \]

In [ ]:
list1 = []

for i in range(2):
   var = int(input("Please enter a number  "))
   list1.append(var)

print(list1)

Please enter a number  4
Please enter a number  5
[4, 5]

In [ ]:
list1 = []

for i in range(2):
   var = int(input("Please enter a number  "))
   list1 += [var]    #only this change

print(list1)

Please enter a number  4
Please enter a number  5
[4, 5]



---



---


##Understanding .split()


` split() function by default converts a string with one whitespace between each element into a list with string elements`

In [ ]:
#split() method by default converts a string with one whitespace between each element into a list with string elements

s = "1 2 3 4 5 6"
list2 = s.split() #same as list2 = s.split(" ")
print(list2)


#Split along COMMA
s = "1,2,3,4,5,6,7"
list2 = s.split(",")
#The string will be splitted along comma(,)
print(list2)


#Split along HASH(#)
s = "1,2,3,4#5,6,7#8,9,10"
list2 = s.split("#")
#The string will be splitted along hash(#) even though there are comma
print(list2)

['1', '2', '3', '4', '5', '6']
['1', '2', '3', '4', '5', '6', '7']
['1,2,3,4', '5,6,7', '8,9,10']

In [ ]:
list1 = ["B", " C", "D", "E"]

for i in list1:
    if i == "E":
      print("Found E")
      break

Found E

In [ ]:
list1 = [ "B", "C", "D", "E", "U"]
list2 = ["A","E", "I", "O", "U"]


for i in list1:
     if i in list2:
      print(f"Found Vowel {i}")
      break

Found Vowel E

In [ ]:
list1 = [ "B", "C", "D", "E", "U"]
list2 = ["A","E", "I", "O", "U"]

for i in list1:
   for j in list2:
          if i==j:
              print(f"Found Vowel {i}")
              break

Found Vowel E
Found Vowel U



#.append() vs .extend()

`Both are inbuilt list methods. You are allowed to use it, unless explicity told not to. `

(Way 01)Using List

In [26]:
list1 = ["A","B","C",["D","E"]]
list1.append(["F","G",["H","I"]]) #Using append, the entire list is added as a <whole>
print("Using append",list1)
print("\n")
print("\n")
print("\n")
print("\n")


list1 = ["A","B","C",["D","E"]]
list1.extend([13,"255",["H","I"]]) #However using extend, the elements are taken out from inputted list> ["F","G",["H","I"]] and individually put into list1 >'F', 'G', ['H', 'I']
print("Using extend",list1)

Using append ['A', 'B', 'C', ['D', 'E'], ['F', 'G', ['H', 'I']]]








Using extend ['A', 'B', 'C', ['D', 'E'], 13, '255', ['H', 'I']]

(Way 02)Using Strings

In [ ]:
list1 = ["A","B"]
list1.append("IJK")      #IJK is added as a  <whole>
print(list1)


list1 = ["A","B"]
list1.extend("IJK")     #IJK is added <individually> as a character into the list
print(list1)

['A', 'B', 'IJK']
['A', 'B', 'I', 'J', 'K']

(Way 03)Using Integers

In [20]:
list1 = ["A","B","C",["D","E"]]
list1.append(12)        #Number can be added to the list with "append()"
print(list1)


list1 = ["A","B","C",["D","E"]]
list1.extend("12")       #uncomment the line. This gives the error, because we cant put a number inside "extend()"
print(list1)

['A', 'B', 'C', ['D', 'E'], 12]
['A', 'B', 'C', ['D', 'E'], '1', '2']

In [42]:
lst=[1,2,3]
lst.extend([2])
lst.extend("25")
for i in range(len(lst)):
    if ord(0)<=ord(str(lst[i]))<=ord(9):
        lst[i]==int(lst[i])
print(lst)

TypeError: ord() expected string of length 1, but int found

In [43]:
lst = [1, 2, 3]
lst.extend([2])
lst.extend("25")

for i in range(len(lst)):
    if ord("0") <= ord(str(lst[i])) <= ord("9"):
        lst[i] = int(lst[i])
        

print(lst)

[1, 2, 3, 2, 2, 5]

In [47]:
lst = ["A", "B", "C"]
#lst.extend([2])
lst.extend("25")

for i in range(len(lst)):
    if 'A' <= str(lst[i]) <= 'Z':
        lst[i] = str(lst[i])

print(lst)

['A', 'B', 'C', '2', '5']

In [34]:
lst = [1, 2, 3]
lst.extend([2])
lst.extend("25")

for i in range(len(lst)):
    if lst[i] in ["2", "5"]:
        lst[i] = int(lst[i])

print(lst)

[1, 2, 3, 2, 2, 5]

## Index()

In [ ]:
list1 = ["A","B","C","D"]

print(list1.index("B"))

AttributeError: ignored